global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 15.0
   publish_frequency: 20.0
   width: 500.0
   height: 500.0
   resolution: 0.05
   static_map: true
   rolling_window: false
